context:
  version: "25.0.8"

package:
  name: semantic-release
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/semantic-release/-/semantic-release-${{ version }}.tgz
  sha256: e96a507593aea37f1d779e08be21f77d5756730ed528d05a1a03a1687ef5d6fc

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - semantic-release --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fully automated version management and package publishing
  homepage: https://github.com/semantic-release/semantic-release
  repository: https://github.com/semantic-release/semantic-release

extra:
  recipe-maintainers:
    - danielnachun
