context:
  version: "24.2.4"

package:
  name: semantic-release
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/semantic-release/-/semantic-release-${{ version }}.tgz
  sha256: 3370d8e6222b0dd51ed778b60ced5007336f095fba76cf5f56b807477f05851d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - semantic-release --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fully automated version management and package publishing
  homepage: https://github.com/semantic-release/semantic-release
  repository: https://github.com/semantic-release/semantic-release

extra:
  recipe-maintainers:
    - danielnachun
