context:
  version: "24.2.5"

package:
  name: semantic-release
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/semantic-release/-/semantic-release-${{ version }}.tgz
  sha256: 31dd349d347403ea5854a86c86bc39112c9a3c75fae5d0da40619afac59eabd3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - semantic-release --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fully automated version management and package publishing
  homepage: https://github.com/semantic-release/semantic-release
  repository: https://github.com/semantic-release/semantic-release

extra:
  recipe-maintainers:
    - danielnachun
