context:
  version: "24.2.3"

package:
  name: semantic-release
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/semantic-release/-/semantic-release-${{ version }}.tgz
  sha256: 93033630293a4e638970b1d9243c3afac22d842dca6da1a2fc92c2a31bf9fe95

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - semantic-release --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fully automated version management and package publishing
  homepage: https://github.com/semantic-release/semantic-release
  repository: https://github.com/semantic-release/semantic-release

extra:
  recipe-maintainers:
    - danielnachun
