context:
  version: "25.0.1"

package:
  name: semantic-release
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/semantic-release/-/semantic-release-${{ version }}.tgz
  sha256: 6992dcf6c673a8470171485c44b8b79941b5f950b88809cdeec238db7259e37c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - semantic-release --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fully automated version management and package publishing
  homepage: https://github.com/semantic-release/semantic-release
  repository: https://github.com/semantic-release/semantic-release

extra:
  recipe-maintainers:
    - danielnachun
